### ISSUE TITLE
(on static pages) recreate table of content functionality - create automatic links to all <h1> in the page

### ISSUE THREAD

**Issue by gregsadetsky** [gregsadetsky/nycnoise#108]
see https://nyc-noise.com/tenants/ for example

**Comment by reyaw** [comment]
this might be a silly question, but I'm looking at `import_wordpress_pages.py` and if it's grabbing the entire contents of the 'content' div, would it not also grab the table of contents? also, what's the best way to get the static page XML so I can test?

**Comment by gregsadetsky** [comment]
heya, no silly questions! the table of contents is generated automatically by wordpress -- so we have to recreate that functionality

as for the static xml, let me send you a few pages over DM

**Comment by reyaw** [comment]
Here is the code I've added to import_wordpress_pages.py:
```python
                table = "<table><th>Table of Contents</th>"

                for h1 in item.xpath("h1"):
                    print(h1.text)
                    href = "#" + h1.text.replace(" ", "_")
                    row = "<span>" + h1.text + "</span>"
                    row = "<tr><td><a href='" + href + "'>" + row + "</a></td></tr>"
                    table += row

                table += "</table>"

                pattern = re.compile('(\[lwptoc.*\])')
                print(pattern)
                
                match = pattern.search(content)
                print(match.groups())

                content = pattern.sub(table, content)

```

Currently facing two issues:

1. I'm using regex to replace the lwptoc tag from the wordpress extension with a new table of contents. Despite using a raw string, Python is still trying to escape the backslashes in my regex pattern. `print(pattern)` yields `re.compile('(\\[lwptoc.*\\])')` and I need those extra slashes out in order to match correctly.  
2. I've tried item.findall('h1') and item.xpath('h1') attempting to find all h1 elements within the XML tree, but they come up empty every time.  I haven't used this XML parsing library before so any insight would be appreciated.
