### ISSUE TITLE
Only link to dates that exist

### ISSUE THREAD

**Issue by robsimmons** [gregsadetsky/nycnoise#64]
Once #43 is resolved and #63 is merged, we should have the calendar link to (only) the dates that have events associated with them.

using the existing site as a template, this link
![image](https://github.com/gregsadetsky/nycnoise/assets/442315/3a5923ec-df64-4fef-8706-2ed4cdd6d270)

should go to this html anchor

![image](https://github.com/gregsadetsky/nycnoise/assets/442315/9e2a0150-c0ee-4454-875d-25b4f0d3e0a9)

But if there's nothing happening october 14, then we shouldn't show the date or a link for that date.

**Comment by gregsadetsky** [comment]
good point! I didn't consider this since it since I don't remember a "non-event" day, but it's definitely a good point.

however... it might also make sense to show the date and show "no events". imagine if today was the day when there are no events and you went to the site - seeing that day not be hyperlinked in the header wouldn't be super clear as to why that's happening. I feel like we might prefer to link to all days, and have an entry for all days.

**Comment by robsimmons** [comment]
Good point! My recommendation was a bit too prescriptive — really this issue is for putting in links once events are grouped by day

Right now the text that the calendar actually shows "oct 11 (wed)" or whatever which is redundant and not super valuable. I think my goal is to have it say "n event(s)" for the appropriate n

**Comment by gregsadetsky** [comment]
for sure! we can also re-visit this as we get closer to alpha/whatever launch with Jessica
