### ISSUE TITLE
minor listing notes!

### ISSUE THREAD

**Issue by nycnoise** [gregsadetsky/nycnoise#77]
QUICK LIL THINGS TO IMPROVE LEGIBILITY &/OR JUST HELP MY BRAIN:

• **bullets** 
• **artists bold** –– _even if there's no link!_
• presenter or event/series title **_not_ bold**!
~• "Add to iCal // add to google calendar" → "**ICAL + GCAL**"~ [ submitted pull request ]
• **date listing** as "abbrev. month xx (day)"
• **lowercase time's "pm"**
______________________________

WHEN ADDING EVENTS:

• would love to have **hyperlink box _above_ description**, since the former is ideally in every listing & the latter is not...
• ...& a **small description box?** how annoying is that hmm
• && any way those lil default time things can be changed...??? having quick-clicks for 7pm / 8pm / 11pm would Rule

______________________________

EVEN _MORE_ ANNOYING, FOR SOMETIME:

• greg i think you have this note elsewhere (sry!!), but reminder abt ability to **override age policy** in creating events (necessary for spaces like knockdown center lacking consistent rules)
• do we wanna slightly alternate **background color** btwn listings for legibility???? maybe like d4d0c7 / e5e2dc... ????? or maybe preferable to just use a different background color for the supplementals (map, ical, gcal, etc.), or have those on diff lines, etc. (toying below)

**Comment by nycnoise** [comment]
&& i'm trying out some Alternate Arrangements at the bottom of [nov 1](https://nyc-noise.com/2023-11/#d1), as shown here:

<img width="665" alt="Screen Shot 2023-10-23 at 9 52 01 PM" src="https://github.com/gregsadetsky/nycnoise/assets/135757981/9e932c33-2ccf-4dd1-b7f5-869a67b222e5">

do we think it's easier to parse all this info with the supplementals on a 2nd line –– & could we maybe make the background of THAT section a slightly different color...????

**Comment by gregsadetsky** [comment]
- DONE bullets
- DONE artists bold when no link
- presenter/event series -> there is no field for that, so, where are you seeing this? just making sure
- DONE date listing i.e. abbrev. month xx (day)
- DONE lowercase pm
- DONE hyperlink box above description
- DONE smaller description box (everything else 4 minutes, this took 40 minutes -- that's programming for ya)
- DONE time shortcuts -- surprisingly wasn't too hard. see below -- added 7, 8, 9, 10 and 11pm presets ---- just click the little 'hour' icon to see them!!

<img width="271" alt="image" src="https://github.com/gregsadetsky/nycnoise/assets/1017304/4221364a-5161-4927-928d-ae858ce9d033">

- DONE added age policy override on event (check the admin)
- (also small note that I did look into handling am/pm time in the django admin instead of 24 hour time, and it's a customization rat's nest -- so I let it rest. sorry!)
- re: alternative background color, etc. -> let's bring this conversation somewhere else since it's more involved! :-)

pushed to prod! it's live! ->

<img width="708" alt="image" src="https://github.com/gregsadetsky/nycnoise/assets/1017304/6468227d-072e-4623-9e9f-a11cbc791d3e">

(and check the prod admin to see the changes there as well)

**Comment by gregsadetsky** [comment]
closing this, feel free to re-open if any of the issues here don't work. and let's talk about design/background, etc. elsewhere cheers!
